### ISSUE TITLE
tool to compile-check the scripts/tests

### ISSUE THREAD

**Issue by elliefm** [fastmail/JMAP-TestSuite#16]
I'd like this mainly to be able to quickly get a dump of any missing/outdated dependencies after an update.  I'm currently doing this manually by digging these commands out of my bash history each time:

```
find . -name \*.pm | grep -v '\.git\/' | xargs -l1 perl -I$PWD/lib -c
find . -name \*.t | grep -v '\.git\/' | xargs -l1 perl -I$PWD/lib -c
```

Obviously I could just bung this into a shell script, but I don't know if there's a perlish/cpanish place to put such a script.

Cassandane checks this in its default make target, but it actually has things that need building.  But it doesn't seem appropriate to handroll a Makefile for a module project that will probably have a Makefile.PL someday.

I'll submit a pull request, I'd just like some guidance on where you'd like such a thing to live. :)

**Comment by elliefm** [comment]
(I realise I could use the cpanm instructions to just refresh the dependencies automatically, but I do not manage installed perl modules through cpan.  That's a different conversation though.)

**Comment by wolfsage** [comment]
What about a xt/compile.t that just does a 'use_ok()' on all of the modules? That covers the modules at least. It could also run against t/ and check all of the test files using file_find or something similar

**Comment by elliefm** [comment]
I've just noticed the repo contains a `cpanfile` (hilariously, predating this issue), so I can just watch for changes in that!
